using System.Collections.Generic;
using Common.Devices;

namespace AuroraRgb.Modules.Razer;

// https://developer.razer.com/works-with-chroma/razer-chroma-led-profiles/
public static class RazerLayoutMap
{
    public static readonly IReadOnlyDictionary<DeviceKeys, int[]> GenericKeyboard = new Dictionary<DeviceKeys, int[]>
    {
        {DeviceKeys.ESC,                   [0, 1] },
        {DeviceKeys.F1,                    [0, 3] },
        {DeviceKeys.F2,                    [0, 4] },
        {DeviceKeys.F3,                    [0, 5] },
        {DeviceKeys.F4,                    [0, 6] },
        {DeviceKeys.F5,                    [0, 7] },
        {DeviceKeys.F6,                    [0, 8] },
        {DeviceKeys.F7,                    [0, 9] },
        {DeviceKeys.F8,                    [0, 10] },
        {DeviceKeys.F9,                    [0, 11] },
        {DeviceKeys.F10,                   [0, 12] },
        {DeviceKeys.F11,                   [0, 13] },
        {DeviceKeys.F12,                   [0, 14] },
        {DeviceKeys.PRINT_SCREEN,          [0, 15] },
        {DeviceKeys.SCROLL_LOCK,           [0, 16] },
        {DeviceKeys.PAUSE_BREAK,           [0, 17] },
        {DeviceKeys.MEDIA_PREVIOUS,        [0, 18] },
        {DeviceKeys.MEDIA_PLAY_PAUSE,      [0, 19] },
        {DeviceKeys.MEDIA_PLAY,            [0, 20] },
        {DeviceKeys.MEDIA_STOP,            [0, 20] },
        {DeviceKeys.MEDIA_PAUSE,           [0, 20] },
        {DeviceKeys.MEDIA_NEXT,            [0, 21] },
        {DeviceKeys.VOLUME_MUTE,           [0, 22] },
        {DeviceKeys.LOGO,                  [0, 20] },
        {DeviceKeys.G1,                    [1, 0] },
        {DeviceKeys.TILDE,                 [1, 1] },
        {DeviceKeys.ONE,                   [1, 2] },
        {DeviceKeys.TWO,                   [1, 3] },
        {DeviceKeys.THREE,                 [1, 4] },
        {DeviceKeys.FOUR,                  [1, 5] },
        {DeviceKeys.FIVE,                  [1, 6] },
        {DeviceKeys.SIX,                   [1, 7] },
        {DeviceKeys.SEVEN,                 [1, 8] },
        {DeviceKeys.EIGHT,                 [1, 9] },
        {DeviceKeys.NINE,                  [1, 10] },
        {DeviceKeys.ZERO,                  [1, 11] },
        {DeviceKeys.MINUS,                 [1, 12] },
        {DeviceKeys.EQUALS,                [1, 13] },
        {DeviceKeys.BACKSPACE,             [1, 14] },
        {DeviceKeys.INSERT,                [1, 15] },
        {DeviceKeys.HOME,                  [1, 16] },
        {DeviceKeys.PAGE_UP,               [1, 17] },
        {DeviceKeys.NUM_LOCK,              [1, 18] },
        {DeviceKeys.NUM_SLASH,             [1, 19] },
        {DeviceKeys.NUM_ASTERISK,          [1, 20] },
        {DeviceKeys.NUM_MINUS,             [1, 21] },
        {DeviceKeys.G2,                    [2, 0] },
        {DeviceKeys.TAB,                   [2, 1] },
        {DeviceKeys.Q,                     [2, 2] },
        {DeviceKeys.W,                     [2, 3] },
        {DeviceKeys.E,                     [2, 4] },
        {DeviceKeys.R,                     [2, 5] },
        {DeviceKeys.T,                     [2, 6] },
        {DeviceKeys.Y,                     [2, 7] },
        {DeviceKeys.U,                     [2, 8] },
        {DeviceKeys.I,                     [2, 9] },
        {DeviceKeys.O,                     [2, 10] },
        {DeviceKeys.P,                     [2, 11] },
        {DeviceKeys.OPEN_BRACKET,          [2, 12] },
        {DeviceKeys.CLOSE_BRACKET,         [2, 13] },
        {DeviceKeys.BACKSLASH,             [2, 14] },
        {DeviceKeys.DELETE,                [2, 15] },
        {DeviceKeys.END,                   [2, 16] },
        {DeviceKeys.PAGE_DOWN,             [2, 17] },
        {DeviceKeys.NUM_SEVEN,             [2, 18] },
        {DeviceKeys.NUM_EIGHT,             [2, 19] },
        {DeviceKeys.NUM_NINE,              [2, 20] },
        {DeviceKeys.NUM_PLUS,              [2, 21] },
        {DeviceKeys.G3,                    [3, 0] },
        {DeviceKeys.CAPS_LOCK,             [3, 1] },
        {DeviceKeys.A,                     [3, 2] },
        {DeviceKeys.S,                     [3, 3] },
        {DeviceKeys.D,                     [3, 4] },
        {DeviceKeys.F,                     [3, 5] },
        {DeviceKeys.G,                     [3, 6] },
        {DeviceKeys.H,                     [3, 7] },
        {DeviceKeys.J,                     [3, 8] },
        {DeviceKeys.K,                     [3, 9] },
        {DeviceKeys.L,                     [3, 10] },
        {DeviceKeys.SEMICOLON,             [3, 11] },
        {DeviceKeys.APOSTROPHE,            [3, 12] },
        {DeviceKeys.HASHTAG,               [3, 13] },
        {DeviceKeys.ENTER,                 [3, 14] },
        {DeviceKeys.CAPS_LOCK_LED,         [3, 15] },
        {DeviceKeys.NUM_LOCK_LED,          [3, 16] },
        {DeviceKeys.SCROLL_LOCK_LED,       [3, 17] },
        {DeviceKeys.NUM_FOUR,              [3, 18] },
        {DeviceKeys.NUM_FIVE,              [3, 19] },
        {DeviceKeys.NUM_SIX,               [3, 20] },
        {DeviceKeys.G4,                    [4, 0] },
        {DeviceKeys.LEFT_SHIFT,            [4, 1] },
        {DeviceKeys.BACKSLASH_UK,          [4, 2] },
        {DeviceKeys.Z,                     [4, 3] },
        {DeviceKeys.X,                     [4, 4] },
        {DeviceKeys.C,                     [4, 5] },
        {DeviceKeys.V,                     [4, 6] },
        {DeviceKeys.B,                     [4, 7] },
        {DeviceKeys.N,                     [4, 8] },
        {DeviceKeys.M,                     [4, 9] },
        {DeviceKeys.COMMA,                 [4, 10] },
        {DeviceKeys.PERIOD,                [4, 11] },
        {DeviceKeys.FORWARD_SLASH,         [4, 12] },
        {DeviceKeys.RIGHT_SHIFT,           [4, 14] },
        {DeviceKeys.ARROW_UP,              [4, 16] },
        {DeviceKeys.NUM_ONE,               [4, 18] },
        {DeviceKeys.NUM_TWO,               [4, 19] },
        {DeviceKeys.NUM_THREE,             [4, 20] },
        {DeviceKeys.NUM_ENTER,             [4, 21] },
        {DeviceKeys.G5,                    [5, 0] },
        {DeviceKeys.LEFT_CONTROL,          [5, 1] },
        {DeviceKeys.LEFT_WINDOWS,          [5, 2] },
        {DeviceKeys.LEFT_ALT,              [5, 3] },
        {DeviceKeys.SPACE,                 [5, 7] },
        {DeviceKeys.RIGHT_ALT,             [5, 11] },
        {DeviceKeys.RIGHT_WINDOWS,         [5, 12] },
        {DeviceKeys.FN_Key,                [5, 12] },
        {DeviceKeys.APPLICATION_SELECT,    [5, 13] },
        {DeviceKeys.RIGHT_CONTROL,         [5, 14] },
        {DeviceKeys.ARROW_LEFT,            [5, 15] },
        {DeviceKeys.ARROW_DOWN,            [5, 16] },
        {DeviceKeys.ARROW_RIGHT,           [5, 17] },
        {DeviceKeys.NUM_ZERO,              [5, 19] },
        {DeviceKeys.NUM_PERIOD,            [5, 20] },
    };

    public static readonly IReadOnlyDictionary<DeviceKeys, int[]> Mouse = new Dictionary<DeviceKeys, int[]>
    {
        {DeviceKeys.Peripheral_ScrollWheel,       [2, 3] },
        {DeviceKeys.Peripheral_Logo,              [7, 3] },
        {DeviceKeys.Peripheral,                   [7, 3] },
        {DeviceKeys.Peripheral_FrontLight,        [4, 3] },
        {DeviceKeys.PERIPHERAL_DPI,               [3, 2] },
        {DeviceKeys.PERIPHERAL_LIGHT1,            [1, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT2,            [2, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT3,            [3, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT4,            [4, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT5,            [5, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT6,            [6, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT7,            [7, 0] },
        {DeviceKeys.PERIPHERAL_LIGHT8,            [1, 6] },
        {DeviceKeys.PERIPHERAL_LIGHT9,            [2, 6] },
        {DeviceKeys.PERIPHERAL_LIGHT10,           [3, 6] },
        {DeviceKeys.PERIPHERAL_LIGHT11,           [4, 6] },
        {DeviceKeys.PERIPHERAL_LIGHT12,           [5, 6] },
        {DeviceKeys.PERIPHERAL_LIGHT13,           [6, 6] },
        {DeviceKeys.PERIPHERAL_LIGHT14,           [7, 6] },
    };

    public static readonly IReadOnlyDictionary<DeviceKeys, int[]> Mousepad = new Dictionary<DeviceKeys, int[]>
    {
        {DeviceKeys.MOUSEPADLIGHT1,               [0, 1] },
        {DeviceKeys.MOUSEPADLIGHT2,               [1, 1] },
        {DeviceKeys.MOUSEPADLIGHT3,               [2, 1] },
        {DeviceKeys.MOUSEPADLIGHT4,               [3, 1] },
        {DeviceKeys.MOUSEPADLIGHT5,               [4, 1] },
        {DeviceKeys.MOUSEPADLIGHT6,               [5, 1] },
        {DeviceKeys.MOUSEPADLIGHT7,               [6, 1] },
        {DeviceKeys.MOUSEPADLIGHT8,               [7, 1] },
        {DeviceKeys.MOUSEPADLIGHT9,               [8, 1] },
        {DeviceKeys.MOUSEPADLIGHT10,              [9, 1] },
        {DeviceKeys.MOUSEPADLIGHT11,              [10, 1] },
        {DeviceKeys.MOUSEPADLIGHT12,              [11, 1] },
        {DeviceKeys.MOUSEPADLIGHT13,              [12, 1] },
        {DeviceKeys.MOUSEPADLIGHT14,              [13, 1] },
        {DeviceKeys.MOUSEPADLIGHT15,              [14, 1] },
        {DeviceKeys.MOUSEPADLIGHT16,              [15, 1] },
        {DeviceKeys.MOUSEPADLIGHT17,              [16, 1] },
        {DeviceKeys.MOUSEPADLIGHT18,              [17, 1] },
        {DeviceKeys.MOUSEPADLIGHT19,              [18, 1] },
        {DeviceKeys.MOUSEPADLIGHT20,              [19, 1] },
    };

    public static readonly IReadOnlyDictionary<DeviceKeys, int[]> Headset = new Dictionary<DeviceKeys, int[]>
    {
        {DeviceKeys.HEADSET1,               [0, 0] },
        {DeviceKeys.HEADSET2,               [0, 1] },
        {DeviceKeys.HEADSET3,               [0, 2] },
        {DeviceKeys.HEADSET4,               [0, 3] },
        {DeviceKeys.HEADSET5,               [0, 4] },
    };

    public static readonly IReadOnlyDictionary<DeviceKeys, int[]> ChromaLink = new Dictionary<DeviceKeys, int[]>
    {
        {DeviceKeys.CL1,               [0, 0] },
        {DeviceKeys.CL2,               [1, 0] },
        {DeviceKeys.CL3,               [2, 0] },
        {DeviceKeys.CL4,               [3, 0] },
        {DeviceKeys.CL5,               [4, 0] },
    };
}